name: Deploy Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Preparar arquivos
        run: |
          mkdir -p public

          if [ "${GITHUB_REF##*/}" = "main" ]; then
            rsync -av --exclude='.git' --exclude='.github' ./ public/
          else
            mkdir -p public/dev
            rsync -av --exclude='.git' --exclude='.github' ./ public/dev/
          fi

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true